server:
  port: 8081

dutra:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
